
server:
  port: 80


#服务别名 --- 注册zookeeper到注册中心名称
spring:
  application:
    name: cloud-consumer-order
    zipkin:
        base-url: http://106.52.195.148:9411
      sleuth:
        sampler:
          #采样取值介于 0到1之间，1则表示全部收集
          probability: 1
  cloud:
    zookeeper:
      connect-string: 106.52.195.148:2181