server:
  port: 9001

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: http://106.52.195.148:8848/ #配置Nacos地址

management:
  endpoints:
    web:
      exposure:
        include: '*'